<?php

namespace AppBundle\Entity\Repository;

use AppBundle\Entity\Cleaning;
use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * PointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointRepository extends EntityRepository
{

}
